### ISSUE TITLE
Ahmadjon oka containerda max-width yozish esdan chiqibdi shu biz tug'rilab quysakchi 🙃

### ISSUE THREAD

**Issue by sherboboyev-azizbek** [Ahmadjon0125/bem-sass-starter#1]
![image](https://user-images.githubusercontent.com/104068436/170237574-f7295636-c1e5-4dd5-9b05-2c9c49b9f843.png)

**Comment by Ahmadjon0125** [comment]
ok, i have done this problem🙃
